version: '3.8'

services:
  frontend:
    image: andregaros/plocadora-frontend:latest
    build: .
    ports:
      - "3333:80"
    environment:
      - API_URL=http://localhost:8080/ator
  back-end:
    image: victorcostac/plocadora:1.0.0
    container_name: locadora-api
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/plocadora
      SPRING_DATASOURCE_USERNAME: plocadora_user
      SPRING_DATASOURCE_PASSWORD: plocadora_pass
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: 10
  db:
    image: postgres:15-alpine
    container_name: locadora-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: plocadora
      POSTGRES_USER: plocadora_user
      POSTGRES_PASSWORD: plocadora_pass
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:


